### ISSUE TITLE
为什么选用 RD4AD 作为 baseline

### ISSUE THREAD

**Issue by ArlixLin** [lewandofskee/DiAD#12]
RD4AD 是单类AD算法，为什么您选用它作为多类的 baseline，而没有选择别的单类方法作为 baseline？
是不是别的单类方法也尝试过，效果不好所有没有写出来？

**Comment by lewandofskee** [comment]
Except for the UniAD algorithm, all other algorithms are single-class anomaly detection (AD) algorithms. RD4AD, which performs very well in CVPR2022, is considered a benchmark model. Many other single-class methods were not released due to their poor performance on multi-class datasets.

**Comment by ArlixLin** [comment]
> Except for the UniAD algorithm, all other algorithms are single-class anomaly detection (AD) algorithms. RD4AD, which performs very well in CVPR2022, is considered a benchmark model. Many other single-class methods were not released due to their poor performance on multi-class datasets.

Can you list any single-class anomaly detection (AD) algorithms you have tried that do not perform well in multi-class datasets. 
Thank you very much

**Comment by lewandofskee** [comment]
Such as CutPaste, RIAD, SPADE, S-T, PSVDD, US.

**Comment by ArlixLin** [comment]
> Such as CutPaste, RIAD, SPADE, S-T, PSVDD, US.

got it, thank you
