### ISSUE TITLE
Stuck in Installing pip dependencies /   for more than 18 hours

### ISSUE THREAD

**Issue by bat1115** [lewandofskee/DiAD#14]
Stuck in Installing pip dependencies /   for more than 18 hours，can you install your environment through environment.yaml successfully？

**Comment by bat1115** [comment]
![1703996897348](https://github.com/lewandofskee/DiAD/assets/58722076/cd0700ce-e58e-443d-94ac-f97d5375c13d)

**Comment by lewandofskee** [comment]
Please try to remove the cudatoolkit=11.3 dependency from environment.yaml. Or install the environment seperately.
pip3 install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
