### ISSUE TITLE
batch size错误和nan问题

### ISSUE THREAD

**Issue by peanutpaste** [lewandofskee/DiAD#18]
1、
UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 12. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`.
这个batch size一直在变，我尝试了一些操作，但是不能消除这个warnig
2、
[2024-01-05 19:31:47,424][ eval_helper.py][line: 333][    INFO] 
|  clsname  |  pixel  |  max  |
|  bottle   | 0.66969 |  nan  |
|   mean    | 0.66969 |  nan  |
这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集）
3、训练完后模型大小是多少，在3060显卡上推理一张图的时间大概是多少呢
我还没训练完，并且训练时有第1，2点的疑惑，不确定是否能训练成功，但是想知道一张图上推理的时间
可以帮忙解答下吗，非常感谢！

**Comment by peanutpaste** [comment]
I have successfully trained on my own dataset. The model is very good at reconstructing static pictures, but for dynamic pictures, its reconstruction effect in dynamic areas needs to be improved (for example, there is a string of fixed lengths at a fixed position in the picture. String, its content is variable, and the reconstruction effect of such an area is not optimal)

**Comment by lewandofskee** [comment]
Thanks! It is the limitation of the model, we need to improve it.

**Comment by GuHuiJian** [comment]
> 1、 UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 12. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`. 这个batch size一直在变，我尝试了一些操作，但是不能消除这个warnig 2、 [2024-01-05 19:31:47,424][ eval_helper.py][line: 333][ INFO] | clsname | pixel | max | | bottle | 0.66969 | nan | | mean | 0.66969 | nan | 这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集） 3、训练完后模型大小是多少，在3060显卡上推理一张图的时间大概是多少呢 我还没训练完，并且训练时有第1，2点的疑惑，不确定是否能训练成功，但是想知道一张图上推理的时间 可以帮忙解答下吗，非常感谢！

你好，我在尝试训练这个模型，我是两个RTX 3090 ，无论怎么修改batch size 一直都在报 cuda out of memory，请问您这里的参数是怎么设置的？谢谢

**Comment by peanutpaste** [comment]
> > 1、 UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 12. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`. 这个batch size一直在变，我尝试了一些操作，但是不能消除这个warnig 2、 [2024-01-05 19:31:47,424][ eval_helper.py][line: 333][ INFO] | clsname | pixel | max | | bottle | 0.66969 | nan | | mean | 0.66969 | nan | 这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集） 3、训练完后模型大小是多少，在3060显卡上推理一张图的时间大概是多少呢 我还没训练完，并且训练时有第1，2点的疑惑，不确定是否能训练成功，但是想知道一张图上推理的时间 可以帮忙解答下吗，非常感谢！
> 
> 你好，我在尝试训练这个模型，我是两个RTX 3090 ，无论怎么修改batch size 一直都在报 cuda out of memory，请问您这里的参数是怎么设置的？谢谢

trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=5)
这是我的训练参数，我是在A6000上单卡训练，而非3060

**Comment by GuHuiJian** [comment]
> > > 1、 UserWarning: Trying to infer the `batch_size` from an ambiguous collection. The batch size we found is 12. To avoid any miscalculations, use `self.log(..., batch_size=batch_size)`. 这个batch size一直在变，我尝试了一些操作，但是不能消除这个warnig 2、 [2024-01-05 19:31:47,424][ eval_helper.py][line: 333][ INFO] | clsname | pixel | max | | bottle | 0.66969 | nan | | mean | 0.66969 | nan | 这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集） 3、训练完后模型大小是多少，在3060显卡上推理一张图的时间大概是多少呢 我还没训练完，并且训练时有第1，2点的疑惑，不确定是否能训练成功，但是想知道一张图上推理的时间 可以帮忙解答下吗，非常感谢！
> > 
> > 
> > 你好，我在尝试训练这个模型，我是两个RTX 3090 ，无论怎么修改batch size 一直都在报 cuda out of memory，请问您这里的参数是怎么设置的？谢谢
> 
> trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是我的训练参数，我是在A6000上单卡训练，而非3060

问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题

**Comment by ClsFaith** [comment]
> > > > `batch_size`1、 UserWarning：试图从不明确的集合中推断。我们发现的批量大小是 12。为了避免任何错误计算，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但是不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][line: 333][ INFO] | 类名称 | 像素| 最大| | 瓶子| 0.66969 | 0.66969 楠 | | 意思是| 0.66969 | 0.66969 楠 | 这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有训练完成，并且训练时有第1，2点的不确定，不确定是否能训练成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > 
> > > 
> > > 你好，我正在尝试训练这个模型，我是两个RTX 3090，无论怎么修改batch size一直都在报cuda内存不足，请问您这里的参数是怎么设置的？谢谢
> > 
> > 
> > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是我的训练参数，我在A6000上单卡训练，负3060
> 
> 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题


> > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行: 333][ INFO] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有完成训练，并且训练时有第1，2点不确定，是否能训练成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > 
> > > 
> > > 好，我正在尝试训练这个模型，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里的参数是怎么设置的？谢谢
> > 
> > 
> > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> 
> 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题

你好，你这个单卡 3090是参数怎么设置的 我的bathsize改成多大都在报cuda内存不足

**Comment by GuHuiJian** [comment]
> > > > > `batch_size`1、 UserWarning：试图从不明确的集合中推断。我们发现的批量大小是 12。为了避免任何错误计算，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但是不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][line: 333][ INFO] | 类名称 | 像素| 最大| | 瓶子| 0.66969 | 0.66969 楠 | | 意思是| 0.66969 | 0.66969 楠 | 这里的max为什么是nan，max代表什么意思（我使用的是MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有训练完成，并且训练时有第1，2点的不确定，不确定是否能训练成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > 
> > > > 
> > > > 你好，我正在尝试训练这个模型，我是两个RTX 3090，无论怎么修改batch size一直都在报cuda内存不足，请问您这里的参数是怎么设置的？谢谢
> > > 
> > > 
> > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是我的训练参数，我在A6000上单卡训练，负3060
> > 
> > 
> > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> 
> > > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行: 333][ INFO] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有完成训练，并且训练时有第1，2点不确定，是否能训练成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > 
> > > > 
> > > > 好，我正在尝试训练这个模型，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里的参数是怎么设置的？谢谢
> > > 
> > > 
> > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> > 
> > 
> > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> 
> 你好，你这个单卡 3090是参数怎么设置的 我的bathsize改成多大都在报cuda内存不足

    setup_seed(1)
    batch_size = 12
    logger_freq = 3000000000000
    learning_rate = 1e-5
    only_mid_control = True
    data_path = './training/MVTec-AD/mvtec_anomaly_detection/'

    # First use cpu to load models. Pytorch Lightning will automatically move it to GPUs.
    model = create_model('models/diad.yaml').cpu()
    model.load_state_dict(load_state_dict(resume_path, location='cpu'),strict=False)
    model.learning_rate = learning_rate
    model.only_mid_control = only_mid_control

    # Misc
    train_dataset, test_dataset = MVTecDataset('train',data_path), MVTecDataset('test',data_path)
    # train_dataset, test_dataset = VisaDataset('train',data_path), VisaDataset('test',data_path)
    train_dataloader = DataLoader(train_dataset, num_workers=2, batch_size=batch_size, shuffle=True)
    test_dataloader = DataLoader(test_dataset, num_workers=2, batch_size=1, shuffle=False)

    ckpt_callback_val_loss = ModelCheckpoint(monitor='val_acc', dirpath='./val_ckpt/',mode='max')
    logger = ImageLogger(batch_frequency=logger_freq)
    #trainer = pl.Trainer(gpus=1, precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)
    trainer = pl.Trainer(devices = [0],accelerator = ('gpu'), precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)

**Comment by ClsFaith** [comment]
> trainer = pl.Trainer(devices = [0],accelerator = ('gpu'), precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)

这个还是不行 能不能分享一下你的环境

**Comment by ClsFaith** [comment]
> 个无



> > 训练器= pl.Trainer（设备= [0]，加速器=（'gpu'），精度= 32，回调= [记录器，ckpt_callback_val_loss]，accumulate_grad_batches = 4，check_val_every_n_epoch = 25）
> 
> 还是这个无法分享你的环境

还是cuda out of 能不能分享你下载的环境

**Comment by ClsFaith** [comment]
> > 个无
> 
> > > 训练器= pl.Trainer（设备= [0]，加速器=（'gpu'），精度= 32，回调= [记录器，ckpt_callback_val_loss]，accumulate_grad_batches = 4，check_val_every_n_epoch = 25）
> > 
> 还是cuda出于无法分享你下载的环境

**Comment by ClsFaith** [comment]
> > > > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行：333][信息] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969 0.66969 楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969 0.66969 楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有完成训练，并且训练时有第1，2点训练不确定，是否能成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > > 
> > > > > 
> > > > > 好，我正在尝试训练这个模型参数，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里是怎么设置的？谢谢
> > > > 
> > > > 
> > > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> > > 
> > > 
> > > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> > 
> > 
> > > > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行: 333][ INFO] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969 0.66969 0.66969 0.66969楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969 0.66969 0.66969 0.66969楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少那么我还没有完成训练，并且训练时有第1点，第2点训练不确定，是否能成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > > 
> > > > > 
> > > > > 好，我正在尝试训练这个模型参数，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里是怎么设置的？谢谢
> > > > 
> > > > 
> > > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> > > 
> > > 
> > > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> > 
> > 
> > 好，你这个单卡3090是参数怎么设置我的bathsize改成多大都在报cuda你内存不足
> 
> ```
> setup_seed(1)
> batch_size = 12
> logger_freq = 3000000000000
> learning_rate = 1e-5
> only_mid_control = True
> data_path = './training/MVTec-AD/mvtec_anomaly_detection/'
> 
> # First use cpu to load models. Pytorch Lightning will automatically move it to GPUs.
> model = create_model('models/diad.yaml').cpu()
> model.load_state_dict(load_state_dict(resume_path, location='cpu'),strict=False)
> model.learning_rate = learning_rate
> model.only_mid_control = only_mid_control
> 
> # Misc
> train_dataset, test_dataset = MVTecDataset('train',data_path), MVTecDataset('test',data_path)
> # train_dataset, test_dataset = VisaDataset('train',data_path), VisaDataset('test',data_path)
> train_dataloader = DataLoader(train_dataset, num_workers=2, batch_size=batch_size, shuffle=True)
> test_dataloader = DataLoader(test_dataset, num_workers=2, batch_size=1, shuffle=False)
> 
> ckpt_callback_val_loss = ModelCheckpoint(monitor='val_acc', dirpath='./val_ckpt/',mode='max')
> logger = ImageLogger(batch_frequency=logger_freq)
> #trainer = pl.Trainer(gpus=1, precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)
> trainer = pl.Trainer(devices = [0],accelerator = ('gpu'), precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)
> ```

分享一下你下载的环境

**Comment by TerryMelody** [comment]
> > > > > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行：333][信息] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969 0.66969 楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969 0.66969 楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少呢我还没有完成训练，并且训练时有第1，2点训练不确定，是否能成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > > > 
> > > > > > 
> > > > > > 好，我正在尝试训练这个模型参数，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里是怎么设置的？谢谢
> > > > > 
> > > > > 
> > > > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> > > > 
> > > > 
> > > > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> > > 
> > > 
> > > > > > > `batch_size`1、 用户警告：尝试从不明确的集合中推断。我们发现批量大小是 12。为了避免任何计算错误，请使用`self.log(..., batch_size=batch_size)`。这个批量大小一直在变化，我尝试了一些操作，但不能消除这个警告 2、 [2024-01-05 19:31:47,424][ eval_helper.py][行: 333][ INFO] |类别名称 |像素|最大| |瓶子| 0.66969 | 0.66969 0.66969 0.66969 0.66969 0.66969 0.66969楠 | |的意思是| 0.66969 | 0.66969 0.66969 0.66969 0.66969 0.66969 0.66969楠 |这里的max为什么是nan，max代表什么意思（我使用MVTec-AD数据集） 3、训练后模型大小是多少，在完成3060显卡上推理一张图的时间大概是多少那么我还没有完成训练，并且训练时有第1点，第2点训练不确定，是否能成功，但想知道一张图上推理的时间可以帮忙解答下吗，非常感谢！
> > > > > > 
> > > > > > 
> > > > > > 好，我正在尝试训练这个模型参数，我是两个 RTX 3090，无论怎么修改批量大小你都在报 cuda 内存不足，请问这里是怎么设置的？谢谢
> > > > > 
> > > > > 
> > > > > trainer = pl.Trainer(max_epochs=1000,gpus=1, precision=32,callbacks=[logger,ckpt_callback_val_loss],accumulate_grad_batches=4, check_val_every_n_epoch=5) 这是训练我的参数，我在A6000上单卡训练，负3060
> > > > 
> > > > 
> > > > 问题解决了，只能在单GPU训练，设置多GPUS，会出现显存溢出的问题
> > > 
> > > 
> > > 好，你这个单卡3090是参数怎么设置我的bathsize改成多大都在报cuda你内存不足
> > 
> > 
> > ```
> > setup_seed(1)
> > batch_size = 12
> > logger_freq = 3000000000000
> > learning_rate = 1e-5
> > only_mid_control = True
> > data_path = './training/MVTec-AD/mvtec_anomaly_detection/'
> > 
> > # First use cpu to load models. Pytorch Lightning will automatically move it to GPUs.
> > model = create_model('models/diad.yaml').cpu()
> > model.load_state_dict(load_state_dict(resume_path, location='cpu'),strict=False)
> > model.learning_rate = learning_rate
> > model.only_mid_control = only_mid_contr
> > 
> > # Misc
> > train_dataset, test_dataset = MVTecDataset('train',data_path), MVTecDataset('test',data_path)
> > # train_dataset, test_dataset = VisaDataset('train',data_path), VisaDataset('test',data_path)
> > train_dataloader = DataLoader(train_dataset, num_workers=2, batch_size=batch_size, shuffle=True)
> > test_dataloader = DataLoader(test_dataset, num_workers=2, batch_size=1, shuffle=False)
> > 
> > ckpt_callback_val_loss = ModelCheckpoint(monitor='val_acc', dirpath='./val_ckpt/',mode='max')
> > logger = ImageLogger(batch_frequency=logger_freq)
> > #trainer = pl.Trainer(gpus=1, precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)
> > trainer = pl.Trainer(devices = [0],accelerator = ('gpu'), precision=32, callbacks=[logger,ckpt_callback_val_loss], accumulate_grad_batches=4, check_val_every_n_epoch=25)
> > ```
> 
> 分享一下你下载的环境

我遇到了同样的问题，我是单卡3090 24G，无论怎么修改批量大小都在报 cuda 内存不足。请问您解决了吗？

**Comment by Mwxinnn** [comment]
Has anyone solved this problem on NVIDIA GeForce RTX 3090 24GB? Could you please share your environment? Thanks!

**Comment by TerryMelody** [comment]
> Has anyone solved this problem on NVIDIA GeForce RTX 3090 24GB? Could you please share your environment? Thanks!

I change it to a single A100 40GB and it can work. I guess 24GB is not enough to run the code.
