### ISSUE TITLE
test.py报错

### ISSUE THREAD

**Issue by wyz22966** [lewandofskee/DiAD#19]
运行python test.py --resume_path ./val_ckpt/epoch=299-step=22799.ckpt，显示
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    dataset = MVTecDataset('test')
TypeError: __init__() missing 1 required positional argument: 'root'

**Comment by pozhizhi** [comment]
你好，我也遇到了一样的错误，你后面怎么解决的。

**Comment by pozhizhi** [comment]
@wyz22966

**Comment by wyz22966** [comment]
> 你好，我也遇到了一样的错误，你后面怎么解决的。

抱歉，过了太久了，已经忘了当时是怎么解决的，可能是路径问题？

**Comment by tommyq666** [comment]
> 你好，我也遇到了一样的错误，你后面怎么解决的。
您好，我目前也遇到了这个问题，请问您是如何解决的？
