### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by s111666** [lewandofskee/DiAD#20]
Using an NVIDIA GeForce RTX 3090 with batch size set to 2 and train. py unable to run the model, modify the code to train=pl. Trainer (gpus=[2,3,4], precision=32, callbacks=[logger, ckpt_callback_val_loss], accumulated_gradnbatches=4, check_val_everyn_epoch=25), or burst memory. May I ask where the problem is?

**Comment by GuHuiJian** [comment]
same proplem ,have you solve it ?

**Comment by s111666** [comment]
> same proplem ,have you solve it ?

Still unresolved.

**Comment by lewandofskee** [comment]
We trained on a single NVIDIA Tesla V100 32GB. Please try using V100 32GB.
