### ISSUE TITLE
微调自动编码器

### ISSUE THREAD

**Issue by anzitong** [lewandofskee/DiAD#25]
在build_model.py文件中。path_input 是不是在finetune_autoencoder.py中得到的autoencoders.ckpt重命名成mvtecad_fs.ckpt
# Stable Diffusion v1.5
input_path = './models/v1-5-pruned.ckpt'

# Output DiAD model
output_path = './models/diad.ckpt'

# Finetuned autoencoders
path_input = './models/mvtecad_fs.ckpt'

**Comment by lewandofskee** [comment]
Yes, exactly.

**Comment by anzitong** [comment]
> Yes, exactly.

微调后的模型是不是保存在这里。./lightning_logs/version_x/checkpoints/epoch=xxx-step=xxx.ckpt，然后将其重命名为mvtecad_fs.ckpt 并移动到models文件夹下？谢谢您的回复。

**Comment by lewandofskee** [comment]
> > Yes, exactly.
> 
> 微调后的模型是不是保存在这里。./lightning_logs/version_x/checkpoints/epoch=xxx-step=xxx.ckpt，然后将其重命名为mvtecad_fs.ckpt 并移动到models文件夹下？谢谢您的回复。

Yes, you are right.

**Comment by anzitong** [comment]
> > > 是的，没错。
> > 
> > 
> > 微调后的模型是不是保存在这里。./lightning_logs/version_x/checkpoints/epoch=xxx-step=xxx.ckpt，然后将其重命名为mvtecad_fs.ckpt 并移动到models文件夹下？谢谢您的回复。
> 
> 是的，你是对的。

好的。非常感谢/
