### ISSUE TITLE
纠错帖

### ISSUE THREAD

**Issue by William9Baker** [lewandofskee/DiAD#3]
`finetune_autoencoder.py` 这个文件中，`train_dataset = MVTecDataset('train')`这一行缺少第二个路径参数，第二个参数是否应该为` 'training/MVTec-AD/mvtec_anomaly_detection'` ，即这行代码正确格式为`train_dataset = MVTecDataset('train', 'training/MVTec-AD/mvtec_anomaly_detection')` ？

**Comment by lewandofskee** [comment]
Thanks, the codes are revised. The data_path param is the location of your dataset.
