### ISSUE TITLE
Controlnet?

### ISSUE THREAD

**Issue by SunTMan** [lewandofskee/DiAD#30]
why not to compare with Controlnet? The proposed model is based on controlnet, even the core code is from it.

**Comment by lewandofskee** [comment]
We compared Controlnet in the very first experiment, but did not do so in the main text because the results were not very good.

**Comment by SunTMan** [comment]
![image](https://github.com/lewandofskee/DiAD/assets/159235109/f1e55879-d71f-494a-a1bc-5dd18760cd95)
I was confused with your response, as I performed experiments based on Controlnet with 500 epoches shown in the figure.
The results are also good.
As shown in the text,  your paper is based on Controlnet.
I don't understand why not with experiments of Controlnet.

**Comment by duoqingxiaowangzi** [comment]
Hello, I have also found that this work can be done using ControlNet. May I ask what control conditions you added when using ControlNet?

**Comment by duoqingxiaowangzi** [comment]
Hello, I have also found that this work can be done using ControlNet. May I ask what control conditions you added when using ControlNet?
@SunTMan
