### ISSUE TITLE
Multi-class in MVTec-AD why use one-class?

### ISSUE THREAD

**Issue by Leminhhuy2386** [lewandofskee/DiAD#33]
Dears,
Thank you for your interesting work.
I see the evaluation result with MVTec-AD dataset. You seem to evaluate with one-class classification (for a single class) in the dataset, not the multi-class (all classes with a single trained model).
Could you please give a comment on this?

Thank you!

**Comment by lewandofskee** [comment]
We appreciate your interest. In this study, a model is trained and tested for multiclass AD, handling 12 distinct categories. During the testing phase, after the model has evaluated all categories and saved the results, performance metrics are computed separately for each class.

**Comment by Leminhhuy2386** [comment]
Thank you for your reply!
