### ISSUE TITLE
用自己的数据集训练

### ISSUE THREAD

**Issue by wyz22966** [lewandofskee/DiAD#34]
我训练完MVTec-AD数据集后准备了一个自己的数据集（路面），照着MVTec-AD的格式进行更改，写了train.json和test.json，数据集路径也改了，也删了npz_result。但是训练了300轮以后生成的log_image中xxx-sample.jpg都是上个数据集MVTec-AD中的图片

**Comment by zhangjy328** [comment]
你的问题是解决了吗？想请教一下，怎么训练自己的数据集，我如果没有掩码只做分类的话该怎么处理？

**Comment by tommyq666** [comment]
> 你的问题是解决了吗？想请教一下，怎么训练自己的数据集，我如果没有掩码只做分类的话该怎么处理？

您好，请问这个问题您解决了吗。如何在没有ground_truth的情况下，训练和测试自己的数据集，需要做哪些修改呢？
