### ISSUE TITLE
论文中的笔误？

### ISSUE THREAD

**Issue by hxx-who** [lewandofskee/DiAD#36]
您好！ 
请问论文中公式7是否存在一些笔误？是否将M_SG(E_SG)写成了M_SG(E_SD)？
以及图2中SGDB4下的蓝色Add操作那里，SDEB4的输出也和SGDB4一起加在SDDB4的输出上吗？这部分在论文里似乎没有体现？
诚盼您的解答！感谢！

**Comment by lewandofskee** [comment]
You are right, thanks for correcting me, it was indeed a typo.
Yes, the output of SDEB4 is also added to the output of SDDB4 along with SGDB4.

**Comment by hxx-who** [comment]
请问论文中所说的所有"Add"是矩阵对应元素相加？还是concat拼接？

**Comment by lewandofskee** [comment]
Add.

**Comment by hxx-who** [comment]
thanks!
