### ISSUE TITLE
公式6的小疑惑

### ISSUE THREAD

**Issue by hxx-who** [lewandofskee/DiAD#37]
您好，论文中公式6中有c_i的出现，我想知道这篇论文中的c_i是什么呢？就是SG网络向去噪网络输出的那些吗？

**Comment by lewandofskee** [comment]
Thank you for your attention. In Formula 6, z_t represents the hidden variable after adding noise, and c_i represents the input image entering the SGN network. These two are the inputs of the SD denoising network and the SGN network respectively.
