### ISSUE TITLE
How to change the epoch and other params？

### ISSUE THREAD

**Issue by BlueSky-Lillia** [lewandofskee/DiAD#39]
Dears,
Thank you for your interesting work.
You say that you set the epoch of train on 1000（paper page 6）,if I want to change the epoch or other params,How can I do that? Should I refer to the implemention of ControlNet?

Could you please give a comment on this?

Thank you!

**Comment by lewandofskee** [comment]
Thank you for your attention and support for our work. You can change parameter settings such as max_epoch in Traner by referring to the official documentation of Pytorch_Lighting. The max_epoch will default to 1000 and you could change it by adding the params in Traner. Hope this can answer your confusion.
