### ISSUE TITLE
Env problem

### ISSUE THREAD

**Issue by Ace-blue** [lewandofskee/DiAD#4]
we noticed in "environment.yaml" the pytorch=1.12.1. While in "xformers==0.0.18" it's required pytorch=2.0.
Which version of pytorch shall I choose?

**Comment by lewandofskee** [comment]
pytorch==2.0 can work for this environment. And the code can also work without 'xformers' installation.

**Comment by fancySummer19** [comment]
![2585999201](https://github.com/lewandofskee/DiAD/assets/92667538/4cc64fa7-4072-45fd-821d-bfcbb3c21c4c)
xFormers报错，怎么解决?
