### ISSUE TITLE
When fine-tuning the model, I can't find where the 'Epoch' parameter is located in which file

### ISSUE THREAD

**Issue by wcnm231** [lewandofskee/DiAD#41]
When running the Python script 'finetune_autoencoder.py' for model fine-tuning, where can I find some output parameters, such as 'Epoch,' in which file?

**Comment by lewandofskee** [comment]
You could change it at pl.Trainer which is the 'max_epoch' parameter. Here is a simple example:
trainer = pl.Trainer(gpus=1, precision=32, max_epochs=500, callbacks=[logger], accumulate_grad_batches=4, check_val_every_n_epoch=50, default_root_dir=default_root_dir, num_sanity_val_steps=0)
