### ISSUE TITLE
我在运行python build_model.py时出现了这个错误，似乎是因为openai/clip-vit-large-patch14无法下载导致的，可以帮助我解决吗

### ISSUE THREAD

**Issue by rock-lss** [lewandofskee/DiAD#42]
Traceback (most recent call last):
  File "/homec/ssli/DiAD/build_model.py", line 27, in <module>
    model = create_model(config_path='/homec/ssli/DiAD/models/diad.yaml')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/DiAD/sgn/model.py", line 26, in create_model
    model = instantiate_from_config(config.model).cpu()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/DiAD/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/DiAD/sgn/sgn.py", line 369, in __init__
    super().__init__(*args, **kwargs)
  File "/homec/ssli/DiAD/ldm/models/diffusion/ddpm.py", line 603, in __init__
    self.instantiate_cond_stage(cond_stage_config)
  File "/homec/ssli/DiAD/ldm/models/diffusion/ddpm.py", line 670, in instantiate_cond_stage
    model = instantiate_from_config(config)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/DiAD/ldm/util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/DiAD/ldm/modules/encoders/modules.py", line 99, in __init__
    self.tokenizer = CLIPTokenizer.from_pretrained(version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/homec/ssli/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2073, in from_pretrained
    raise EnvironmentError(
OSError: Can't load tokenizer for 'openai/clip-vit-large-patch14'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwise, make sure 'openai/clip-vit-large-patch14' is the correct path to a directory containing all relevant files for a CLIPTokenizer tokenizer.

**Comment by lewandofskee** [comment]
I think it may be that your server is not connecting to huggingface.co, causing your deployment to fail. You can refer to this [blog](https://blog.csdn.net/SuperB666/article/details/132826492) as well as this [issue](https://github.com/CompVis/stable-diffusion/issues/90) to try to download the pretrained weights to your local director first.

**Comment by DubheBroken** [comment]
1. 打开 `https://huggingface.co/openai/clip-vit-large-patch14` 手动下载所有文件，存到本地，记下目录，例如：`D:\clip-vit-large-patch14`
2. 打开这个文件`venv\Lib\site-packages\transformers\tokenization_utils_base.py` 
找到 `pretrained_model_name_or_path = str(pretrained_model_name_or_path)`
改成`pretrained_model_name_or_path = "D:\models--openai--clip-vit-large-patch14"`
3. 最后重启软件就可以了，一定要重启软件！

**Comment by DubheBroken** [comment]
邮件是不是发错人了？我好像不是你们项目团队的一员。

I am not a member of your team. You’ve sent this email to the wrong
recipient.

lewandofskee ***@***.***> 于2024年12月6日周五 15:03写道：
