### ISSUE TITLE
The comparison part is questionable

### ISSUE THREAD

**Issue by neuraaal** [lewandofskee/DiAD#48]
hello author, your paper is very beautiful and enlightening, but I still have several problems that are not clearly explained in the paper. In the comparative experiment, do you reproduce the RD4AD model according to the original paper or according to your multi-category anomaly detection? It is understood that RD4AD belongs to a single class

**Comment by lewandofskee** [comment]
Thank you for your interest in our work. RD4AD is designed for single-class anomaly detection tasks. We obtained our results by using the official RD4AD code to conduct experiments on multi-class anomaly detection tasks.
