### ISSUE TITLE
About the "multi-class setting" mentioned in the paper

### ISSUE THREAD

**Issue by ArlixLin** [lewandofskee/DiAD#5]
Thank you for your selfless sharing!
I saw the data presentation in Table 1 and Table 3 in your paper, which mentioned "multi-class setting". May I ask what it means? Is the MVTEC's 15 types of data mixed together for training and then mixed together for testing? I see that RD4AD seems to have only "OneClass Novelty Detection" and no "multi-class setting". 
Looking forward to your reply

**Comment by lewandofskee** [comment]
Yes, your understanding is correct. All classes of data mixed together for training and testing. The original RD4AD is one class to one model which is 'single-class setting'.
