### ISSUE TITLE
about SGDB4

### ISSUE THREAD

**Issue by xgzng** [lewandofskee/DiAD#51]
Hello, I can't find the SGDB4 related code in the repository, can you help me point it out?

**Comment by lewandofskee** [comment]
Thank you for your attention. Please refer to lines 40-48 and 355-358 in the code. https://github.com/lewandofskee/DiAD/blob/main/sgn/sgn.py

**Comment by xgzng** [comment]
Hello, thank you for your reply, I read the relevant code and found that the features after the SFF module were directly added to the SD Denoising network, and did not go through the SGDB module.

**Comment by lewandofskee** [comment]
Please refer to the code design specifications.
