### ISSUE TITLE
The link is no longer accessible.

### ISSUE THREAD

**Issue by luow23** [lewandofskee/DiAD#54]
![1731164230841](https://github.com/user-attachments/assets/3e51feeb-f88c-4b55-94e6-fc341011ca95)
![1731164238920](https://github.com/user-attachments/assets/ebc9e29a-7eac-4ff7-b2d4-56ebb41470d2)

**Comment by buaayunjc** [comment]
how should we do?

**Comment by giddyyupp** [comment]
you can follow the links in this post: https://www.reddit.com/r/StableDiffusion/comments/1f4epto/comment/lklkpcl

also in HF: https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5

**Comment by lewandofskee** [comment]
I will update the weight links to the new Hugging Face (HF) address: [https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5](https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5)
