### ISSUE TITLE
Autoencoder weights for COCO

### ISSUE THREAD

**Issue by giddyyupp** [lewandofskee/DiAD#56]
Hello,

Have you finetuned the autoencoder part on the COCO-AD dataset or just fused with the one in ControlNet?
If you finetuned could you share the weights?

Thanks.

**Comment by lewandofskee** [comment]
Hello, we fine-tune the autoencoder on the COCO-AD dataset. The pre-trained weights are uploaded in [fs_coco0](https://drive.google.com/file/d/17LPiud6zwA4XqUbrJ8Mbrno_V-uz3OVG/view?usp=sharing), [fs_coco1](https://drive.google.com/file/d/1RBQzH3cHXoYmBSzqHw08s7Um9flQFoYl/view?usp=sharing), [fs_coco2](https://drive.google.com/file/d/1pCL-80d4T4DjCTN2rbmNk3TOmjADZLvC/view?usp=sharing), [fs_coco3](https://drive.google.com/file/d/1SCS5LtaPFZbx5OYSHbiun5kGGOXOxkY6/view?usp=sharing).

**Comment by giddyyupp** [comment]
perfect, thank you very much.

**Comment by giddyyupp** [comment]
Btw is it possible to upload AE weights for Cifar10 and Cifar100 too? And for Cifar 10 did you train with half split of classes or 1 vs rest?

**Comment by lewandofskee** [comment]
Sorry, We have not trained on CIFAR-10 and CIFAR-100 datasets.
