### ISSUE TITLE
文章的创新点疑问

### ISSUE THREAD

**Issue by jackyyang-cv** [lewandofskee/DiAD#6]
文章的创新点就是增加了语义指导网络Semantic-Guided Network，该网络的特征加入到unet的decoder三层特征中，这和增加算力提升准确率有什么区别呢，loss也是均方差loss，没有修改。没有什么创新点吧

**Comment by lewandofskee** [comment]
Please read our paper carefully, especially the motivation in the Introduction section. Thanks.

**Comment by jackyyang-cv** [comment]
不仅看了paper，还读了源码，总结下来确实没有什么创新点。你可否用一句话通俗的说清你的创新点呢
