### ISSUE TITLE
Result format

### ISSUE THREAD

**Issue by giddyyupp** [lewandofskee/DiAD#60]
Hello,
I would like to match the result string to your main result table. What I get is below one:
  clsname  |   pro    |   f1px   |  pixel   |   appx   |   max    |  f1sp   |   apsp   |
  
  and the table mentions:
  mAU-ROCI 	mAPI 	mF1-maxI 	mAU-ROCP 	mAPP 	mF1-maxP 	mAU-PROR

could you elaborate on this?

**Comment by giddyyupp** [comment]
This is how I matched, is it correct?

mAU-ROCI 	mAPI 	mF1-maxI 	mAU-ROCP 	mAPP 	mF1-maxP 	mAU-PROR
"f1sp"            "apsp"       "max"              "pixel"             "appx"      "f1px"              "pro"

**Comment by lewandofskee** [comment]
Sorry for the inconvenience caused. In fact, their corresponding relationship is

mAU-ROCI mAPI mF1-maxI mAU-ROCP mAPP mF1-maxP mAU-PROR
"max" "apsp" "f1sp" "pixel" "appx" "f1px" "pro"
