### ISSUE TITLE
Training params for COCO-AD and separate results for each set

### ISSUE THREAD

**Issue by giddyyupp** [lewandofskee/DiAD#61]
Hello,

I would like to know whether you trained for 1000 epochs on COCO-AD or not because it is taking a loooot of time :) if not how many epochs did you train for?

Also is it possible for you to share the results on each subset of COCO-AD. 

Thanks

**Comment by lewandofskee** [comment]
Training COCO-AD indeed requires a significant amount of time. Therefore, we only trained each subset for 60 epochs. The results for each subset can be found in the supplementary materials of the [ADer](https://arxiv.org/pdf/2406.03262) paper on page **55**.

**Comment by giddyyupp** [comment]
perfect thank you for the clarification!
