### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by fancySummer19** [lewandofskee/DiAD#7]
![2734968604](https://github.com/lewandofskee/DiAD/assets/92667538/d18d92b3-f96e-464a-85ae-367d848be631)

在运行python finetune_autoencoder.py，报错如上所示。
您能否提一些建议。

**Comment by lewandofskee** [comment]
Please re-download the project where we had revised some errors several days ago.

**Comment by fancySummer19** [comment]
ok thanks
