### ISSUE TITLE
ERROR: Cannot install opencv-python==4.5.1.48 and opencv_python==4.7.0.72 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by bat1115** [lewandofskee/DiAD#8]
![image](https://github.com/lewandofskee/DiAD/assets/58722076/4b7d5568-6351-4549-84bf-468b0a285821)

**Comment by bat1115** [comment]
There is two versions of opencv-python, is this right?

**Comment by lewandofskee** [comment]
Thanks, we have revised the opencv-python and opencv-python-headless versions to 4.5.1.48.
